name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --workspace
    - name: Run tests
      run: |
        docker run -d --name ipfs_host -p 127.0.0.1:5001:5001 ipfs/go-ipfs:v0.11.0
        cargo test --workspace
        docker stop ipfs_host
